### ISSUE TITLE
Selection of 'PM' Time Missing from Datetime Control

### ISSUE THREAD

**Issue by rmolley** [Telerik-Verified-Plugins/Crosswalk#2]
This is a bit odd but the date time control is missing 'PM' selection for time (see attached). I simply call it with this code:

`<input id="add-schedule-datetime" type="datetime-local" />`

Any ideas as to why it's missing? The time isn't 24-Hour so you can't select a 'PM' time no matter what you try.

![img_0829](https://cloud.githubusercontent.com/assets/5041208/15617310/5982292e-2416-11e6-9322-70df5fdf4679.JPG)

**Comment by EddyVerbruggen** [comment]
This is `<input type="date"/>`?

And the exact same code without xwalk shows both AM and PM?

**Comment by rmolley** [comment]
If I use your code it only shows the date and I need date and time. I tested this on Nexus 7 2014, Nexus 5, and Samsung Galaxy 5 with all the same results missing the 'PM'.

**Comment by EddyVerbruggen** [comment]
Let me ask it differently :)
1. How do you show the date/time widget?
2. If you remove crosswalk and keep everything else the same, do you get the same result?

**Comment by rmolley** [comment]
If I remove crosswalk and use the Default WebView in Telerik it displays as expected, with both 'AM' and 'PM' selections. It's only with the crosswalk plugin that it behaves like this.

**Comment by EddyVerbruggen** [comment]
Thanks, can you please also enlighten me how the date widget is shown exactly?

**Comment by rmolley** [comment]
Let me know if this is what you want. You basically click the input and the date time widget displays in the app. This is a hybrid app that uses jQuery Mobile on Cordova 5.0.0.

**Comment by EddyVerbruggen** [comment]
I was wondering if that picker was a plugin or an html input type, so it's the latter, right?

Did you search the upstream repo's issues / google / StackOverflow for something similar already? It must be something with the Chromiun version that xwalk ships.

**Comment by rmolley** [comment]
Yes it's the latter, just an html input type. I have checked StackOverflow but found nothing related; however, I haven't searched specifically for reported issues in the Chromium version though.

**Comment by EddyVerbruggen** [comment]
A quick Google found me [this Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=529320).

So which crosswalk version / chromium version are you on?

**Comment by rmolley** [comment]
According to that bug report this was resolved in version 46. What version are you using? This bug may have resurfaced again.

**Comment by EddyVerbruggen** [comment]
Correct, but it may be only related to 45 (not sure). The latest version of this plugin uses 45, but we'll update to 46 in the foreseeable future. Interesting to know if the issue also pops up on 44 (plugin version 1.4.0.3).

**Comment by rmolley** [comment]
Yes this issue also pops up in your plugin versions 1.4.0.3 and 1.2.0. Any ideas when your next update might be?

**Comment by EddyVerbruggen** [comment]
Hey @rmolley, I just updated to the latest Crosswalk bits and the `datetime-local` widget looks great on my device. Hopefully for you too!

**Comment by rmolley** [comment]
Yes, it works. Thank you!
