### ISSUE TITLE
new version of crosswalk

### ISSUE THREAD

**Issue by keenan35i** [Telerik-Verified-Plugins/Crosswalk#4]
Would you consider adding a preference to choose what version to build in the config file such as `<preference name="buildType" value="64" />`, after the  new version of this plugin came out it no longer builds useing phone gap build, assumable it is from the addition of 64 bit builds. Any help would this would be great that way i can update the crosswalk version to a more current build.

thanks!

**Comment by EddyVerbruggen** [comment]
You can always pin to a [specific release](https://github.com/Telerik-Verified-Plugins/Crosswalk/releases), but IMO it's not a problem this plugin should solve.

That being said a PR would of course be considered.
