### ISSUE TITLE
Do we need this crosswalk for 5.x-6x devices

### ISSUE THREAD

**Issue by ezazwar1** [Telerik-Verified-Plugins/Crosswalk#5]
Hey @EddyVerbruggen  i have a confusion as i read few articles about crosswalk is that this mainly boosts the android 4.x devices and are helpful in that regards.But for android 5.x and 6.x its not needed. If i am correct then i was thinking of building the android project with crosswalk for android 4.x device and for later versions like 5.x and 6.x i would use the regular non Crosswalk Build. Is it possible to do so as the apk size becomes huge if crosswalk is added so there may be some sort of relaxation for the persons using 5.x or later . So i need your suggestions in this matter that should i go with what i am thinking 

Correct me if i am wrong

Regards
Ezaz

**Comment by EddyVerbruggen** [comment]
Hi, firstly Crosswalk gives you a way to ship 1 spec of Chromium to all your targeted devices. So it still has value for even Android 7 as you only have to test your app once and it doesn't matter on which device. Performance-wise Crosswalk will be on par with the browser shipped on the latest Android devices of course.

If you want to ship Crosswalk only for lower Android version then that's very understandable. Google allows you to ship multiple APK's for one app. I really feel you should look at the Google Play docs and the official Crosswalk doc as they know a lot more about this subject than I do.
